---

- name: Arista Ethernet Configuration tool
  hosts: arista

  tasks:
    - name: Configure Ethernet Interface as trunk
      eos_switchport: name={{ item }} mode=trunk trunk_native_vlan=1
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{ eapi_port }}
           transport=https
      with_items:
        - Ethernet2
        - Ethernet5

    - name: Configure Ethernet Interface Switchport Options
      eos_switchport: name={{ item.name }} mode=trunk trunk_native_vlan=100 trunk_allowed_vlans=105,115,777
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{ eapi_port }}
           transport=https
      with_items:
        - Ethernet2
        - Ethernet5