---

- name: Arista VLAN add
  hosts: arista

  tasks:
    - name: Create VLANs
      eos_vlan: name={{ item.name }} vlanid={{ item.vlanid }} state=absent
           username={{ eapi_username }}
           password={{ eapi_password }}
           host={{ eapi_hostname }}
           port={{ eapi_port }}
           transport=https
      with_items:
        - {name: BLUE, vlanid: 105}
        - {name: Wifi_Users, vlanid: 115}
        - {name: Winning, vlanid: 777}
