---

- name: Cisco IOS testing
  hosts: Cisco
  gather_facts: False

  tasks:
  - name: Testing file transfer
    cisco_file_transfer:
      source_file="/home/bsavelli.ANSIBLE/cisco-logjam.txt"
      dest_file=cisco-logjam.txt
      overwrite=true
      enable_scp=true
      host={{ host }}
      port={{ port }}
      username={{ username }}
      password={{ password }}
      